### ISSUE TITLE
Unable to use ace

### ISSUE THREAD

**Issue by jayy12** [ace-lol/Ace#21]
when I try to launch ace, I get a popup telling me that access has been denied.
Can you tell me how to fix this 

the popup : 
![ace bug](https://cloud.githubusercontent.com/assets/23620674/20466701/aa9cfc3e-af45-11e6-8dcf-eee86d05fe5c.PNG)

thanks for the help.

**Comment by molenzwiebel** [comment]
Running Ace as administator should fix this issue. If not, please let me know.
